# Example params for spatialvi_nf_pipeline
# Use: nextflow run . -params-file examples/params.yml -profile docker

input: "samplesheet.csv"
results_parent_id: "syn99999999"   # Synapse folder for result tarballs
spatialvi_pipeline: "sagebio-ada/spatialvi"  # Sage Bionetworks fork
spatialvi_release: "dev"          # branch or tag (e.g. dev, main, 1.0.0)
